import type { Creator, Campaign } from '@/types';

// ─── 12 Realistic B2B LinkedIn Creators ─────────────────────────────────────

export const MOCK_CREATORS: Creator[] = [
  {
    id: 'c-001',
    name: 'Marcus Riedel',
    handle: '@marcus-riedel',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=96&h=96&fit=crop&crop=face',
    headline: 'VP Product @ Personio · Writing about PLG, B2B pricing & SaaS metrics that actually move ARR',
    niche: 'B2B SaaS',
    location: 'Munich, Germany',
    followers: 87400,
    fitScore: 96,
    basePriceEur: 3200,
    avgImpressions: 142000,
    ctrPercent: 2.8,
    engagementRate: 4.1,
    audienceB2BPercent: 78,
    avgLeadsPerPost: 38,
    verified: true,
    responseTimeHours: 6,
    tags: ['PLG', 'SaaS Metrics', 'Pricing Strategy', 'Product-Led Growth', 'ARR'],
    samplePosts: [
      {
        text: 'We killed our 14-day free trial and replaced it with a 30-day usage-based onboarding. Here\'s what happened to our conversion rate — and why every B2B SaaS founder should consider this move. 🧵',
        likes: 4821,
        impressions: 168000,
        comments: 312,
        reposts: 891,
        postedAt: '2024-11-12T09:00:00Z',
      },
      {
        text: 'The "land and expand" motion is broken for most SaaS companies. They focus on the land, forget the expand. Real talk on why NRR > everything else right now.',
        likes: 3654,
        impressions: 121000,
        comments: 247,
        reposts: 643,
        postedAt: '2024-11-05T08:30:00Z',
      },
    ],
  },
  {
    id: 'c-002',
    name: 'Priya Nambiar',
    handle: '@priya-nambiar',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=96&h=96&fit=crop&crop=face',
    headline: 'Head of Developer Relations @ Vercel · AI-native tooling, open-source strategy & the future of the JS ecosystem',
    niche: 'DevRel & AI',
    location: 'San Francisco, CA',
    followers: 112300,
    fitScore: 94,
    basePriceEur: 4100,
    avgImpressions: 198000,
    ctrPercent: 3.4,
    engagementRate: 5.2,
    audienceB2BPercent: 71,
    avgLeadsPerPost: 52,
    verified: true,
    responseTimeHours: 12,
    tags: ['Developer Relations', 'AI Tooling', 'Open Source', 'React', 'Next.js', 'LLMs'],
    samplePosts: [
      {
        text: 'I\'ve seen 400+ developer tools pitch their DevRel strategy. 90% make the same mistake: they hire a DevRel to do marketing. Here\'s the difference between DevRel that compounds and DevRel that costs you your best engineers. 🧵',
        likes: 7203,
        impressions: 241000,
        comments: 531,
        reposts: 1432,
        postedAt: '2024-11-18T10:00:00Z',
      },
      {
        text: 'We just shipped an AI coding assistant inside our docs. 3 weeks of work. Here\'s the full stack breakdown: embeddings, RAG, streaming UI, and what surprised us about adoption curves.',
        likes: 5812,
        impressions: 187000,
        comments: 398,
        reposts: 1021,
        postedAt: '2024-11-08T09:15:00Z',
      },
    ],
  },
  {
    id: 'c-003',
    name: 'Stefan Hartmann',
    handle: '@stefan-hartmann',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=96&h=96&fit=crop&crop=face',
    headline: 'CRO @ Moss · Scaling B2B fintech GTM from €5M to €50M ARR · Angel investor in 14 European startups',
    niche: 'Fintech',
    location: 'Berlin, Germany',
    followers: 64800,
    fitScore: 91,
    basePriceEur: 2800,
    avgImpressions: 98000,
    ctrPercent: 3.1,
    engagementRate: 4.7,
    audienceB2BPercent: 83,
    avgLeadsPerPost: 41,
    verified: true,
    responseTimeHours: 18,
    tags: ['B2B Fintech', 'GTM', 'Revenue Growth', 'CFO Audience', 'Spend Management'],
    samplePosts: [
      {
        text: 'CFOs don\'t buy software. They buy reduced risk. If your fintech pitch deck still leads with "streamline your workflows" — you\'re selling to the wrong person in the wrong language. Here\'s what actually works.',
        likes: 3287,
        impressions: 104000,
        comments: 198,
        reposts: 512,
        postedAt: '2024-11-14T08:00:00Z',
      },
      {
        text: 'We went from 3-month sales cycles to 3-week closes in fintech. The change wasn\'t our product — it was our champion-building playbook. Full breakdown 👇',
        likes: 2943,
        impressions: 91000,
        comments: 173,
        reposts: 438,
        postedAt: '2024-11-06T09:00:00Z',
      },
    ],
  },
  {
    id: 'c-004',
    name: 'Leila Vasquez',
    handle: '@leila-vasquez',
    avatarUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=96&h=96&fit=crop&crop=face',
    headline: 'GTM Partner @ a16z · Former VP Sales Salesforce EMEA · I write the outbound playbooks senior AEs actually use',
    niche: 'GTM & Sales',
    location: 'London, UK',
    followers: 93700,
    fitScore: 93,
    basePriceEur: 3600,
    avgImpressions: 156000,
    ctrPercent: 2.9,
    engagementRate: 4.5,
    audienceB2BPercent: 76,
    avgLeadsPerPost: 44,
    verified: true,
    responseTimeHours: 8,
    tags: ['GTM Strategy', 'Outbound Sales', 'Enterprise Sales', 'MEDDIC', 'Revenue Operations'],
    samplePosts: [
      {
        text: 'I reviewed 1,000 cold emails this quarter. 94% of them failed because of ONE thing — they talked about themselves, not the buyer\'s problem. Here\'s the 5-line cold email framework that\'s generating 38% reply rates for my portfolio companies.',
        likes: 6512,
        impressions: 189000,
        comments: 642,
        reposts: 1871,
        postedAt: '2024-11-20T07:30:00Z',
      },
      {
        text: 'Enterprise sales is not a skill. It\'s a system. The companies that consistently close 6-figure deals have operationalized every step from ICP definition to multi-threading. Here\'s the complete GTM stack breakdown.',
        likes: 4923,
        impressions: 143000,
        comments: 387,
        reposts: 934,
        postedAt: '2024-11-09T08:00:00Z',
      },
    ],
  },
  {
    id: 'c-005',
    name: 'David Chen',
    handle: '@david-chen-saas',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=96&h=96&fit=crop&crop=face',
    headline: 'Founder @ Narrate AI · Ex-Stripe Growth · Writing about AI-native SaaS, pricing models & the next wave of B2B infrastructure',
    niche: 'B2B SaaS',
    location: 'New York, NY',
    followers: 74200,
    fitScore: 89,
    basePriceEur: 2900,
    avgImpressions: 118000,
    ctrPercent: 2.5,
    engagementRate: 3.8,
    audienceB2BPercent: 72,
    avgLeadsPerPost: 31,
    verified: true,
    responseTimeHours: 24,
    tags: ['AI-Native SaaS', 'Infrastructure', 'Stripe Alumni', 'Pricing', 'Fintech Infrastructure'],
    samplePosts: [
      {
        text: 'Stripe\'s biggest insight wasn\'t payments. It was that developers are buyers. Every B2B company is now figuring out: how do we build the Stripe of our industry? Here\'s the 3-part formula.',
        likes: 3891,
        impressions: 127000,
        comments: 298,
        reposts: 712,
        postedAt: '2024-11-16T09:00:00Z',
      },
      {
        text: 'We just crossed $1M ARR in 14 months with zero outbound. Here\'s the exact product-led content strategy that made it happen — and the single metric that predicted our growth before it happened.',
        likes: 5234,
        impressions: 162000,
        comments: 441,
        reposts: 1123,
        postedAt: '2024-11-10T08:00:00Z',
      },
    ],
  },
  {
    id: 'c-006',
    name: 'Aisha Okonkwo',
    handle: '@aisha-okonkwo',
    avatarUrl: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=96&h=96&fit=crop&crop=face',
    headline: 'AI Research Lead @ Cohere · Building the foundation models that power enterprise AI · Writing about LLMs in production',
    niche: 'DevRel & AI',
    location: 'Toronto, Canada',
    followers: 145600,
    fitScore: 92,
    basePriceEur: 5200,
    avgImpressions: 267000,
    ctrPercent: 3.8,
    engagementRate: 5.9,
    audienceB2BPercent: 68,
    avgLeadsPerPost: 67,
    verified: true,
    responseTimeHours: 36,
    tags: ['LLMs', 'Enterprise AI', 'Foundation Models', 'RAG', 'AI in Production', 'ML Engineering'],
    samplePosts: [
      {
        text: 'We benchmarked 6 enterprise LLMs on 10,000 real B2B support tickets. The results surprised everyone, including us. Full breakdown with charts: accuracy, latency, cost per query, and the hallucination rates nobody publishes.',
        likes: 9123,
        impressions: 312000,
        comments: 743,
        reposts: 2341,
        postedAt: '2024-11-19T10:00:00Z',
      },
      {
        text: 'RAG is not a silver bullet. After deploying 40+ enterprise RAG systems, here\'s what actually fails in production — and the retrieval patterns that actually work at scale.',
        likes: 7654,
        impressions: 248000,
        comments: 612,
        reposts: 1879,
        postedAt: '2024-11-11T09:00:00Z',
      },
    ],
  },
  {
    id: 'c-007',
    name: 'James Whitfield',
    handle: '@james-whitfield-gtm',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=96&h=96&fit=crop&crop=face',
    headline: 'VP Revenue @ Deel · MEDDIC evangelist · I help B2B revenue teams build systematic sales motions that scale past €20M ARR',
    niche: 'GTM & Sales',
    location: 'Amsterdam, Netherlands',
    followers: 58300,
    fitScore: 88,
    basePriceEur: 2400,
    avgImpressions: 89000,
    ctrPercent: 2.7,
    engagementRate: 4.2,
    audienceB2BPercent: 80,
    avgLeadsPerPost: 29,
    verified: false,
    responseTimeHours: 12,
    tags: ['MEDDIC', 'Revenue Operations', 'Sales Enablement', 'CRO Playbook', 'B2B Sales'],
    samplePosts: [
      {
        text: 'MEDDIC gets the credit. Multi-threading wins the deal. Here\'s why 80% of deals that stall in procurement were actually lost 3 months earlier when the AE stopped building economic buyer relationships.',
        likes: 2876,
        impressions: 94000,
        comments: 187,
        reposts: 423,
        postedAt: '2024-11-13T08:30:00Z',
      },
      {
        text: 'I\'ve hired 200+ AEs across 3 continents. The #1 predictor of a top performer isn\'t past quota attainment. It\'s this one trait you can spot in the first 10 minutes of an interview.',
        likes: 4123,
        impressions: 132000,
        comments: 318,
        reposts: 876,
        postedAt: '2024-11-07T08:00:00Z',
      },
    ],
  },
  {
    id: 'c-008',
    name: 'Sophia Bernhardt',
    handle: '@sophia-bernhardt',
    avatarUrl: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=96&h=96&fit=crop&crop=face',
    headline: 'CPO @ Soldo · European fintech builder · Payments infrastructure, open banking & the boring parts of fintech nobody talks about',
    niche: 'Fintech',
    location: 'Vienna, Austria',
    followers: 41200,
    fitScore: 85,
    basePriceEur: 1900,
    avgImpressions: 64000,
    ctrPercent: 2.4,
    engagementRate: 3.6,
    audienceB2BPercent: 85,
    avgLeadsPerPost: 22,
    verified: false,
    responseTimeHours: 24,
    tags: ['Open Banking', 'Payments', 'Fintech Infrastructure', 'B2B Payments', 'Regulatory'],
    samplePosts: [
      {
        text: 'PSD3 is coming. Most B2B fintech companies think it\'s a compliance checkbox. The ones that treat it as a distribution opportunity will gain 5 years of competitive advantage. Here\'s why.',
        likes: 1987,
        impressions: 67000,
        comments: 143,
        reposts: 287,
        postedAt: '2024-11-15T09:00:00Z',
      },
      {
        text: 'We rebuilt our payment reconciliation system from scratch. 8 engineers, 6 months, €2M in savings. Here\'s what we learned about the hidden cost of legacy fintech infrastructure.',
        likes: 2234,
        impressions: 71000,
        comments: 167,
        reposts: 341,
        postedAt: '2024-11-04T10:00:00Z',
      },
    ],
  },
  {
    id: 'c-009',
    name: 'Arjun Mehta',
    handle: '@arjun-mehta-ai',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=96&h=96&fit=crop&crop=face',
    headline: 'AI Product Lead @ Notion · Building AI-native workflows for 50M+ users · Thoughts on product, AI UX & what comes after SaaS',
    niche: 'DevRel & AI',
    location: 'Bangalore, India',
    followers: 89100,
    fitScore: 90,
    basePriceEur: 3400,
    avgImpressions: 148000,
    ctrPercent: 3.2,
    engagementRate: 4.9,
    audienceB2BPercent: 70,
    avgLeadsPerPost: 43,
    verified: true,
    responseTimeHours: 18,
    tags: ['AI UX', 'Product Management', 'AI Workflows', 'No-Code', 'AI Native Products'],
    samplePosts: [
      {
        text: 'The AI feature nobody asked for is killing your retention. We analyzed 1,000 B2B SaaS products that added "AI" to their roadmap in 2024. Here\'s the pattern of what worked and what silently churned users.',
        likes: 5678,
        impressions: 183000,
        comments: 412,
        reposts: 1234,
        postedAt: '2024-11-17T09:30:00Z',
      },
      {
        text: 'Notion\'s AI onboarding went from 12% activation to 68% activation in 90 days. Not by adding features. By removing 4 of them. Here\'s the full story of what we cut and why.',
        likes: 4321,
        impressions: 141000,
        comments: 356,
        reposts: 987,
        postedAt: '2024-11-03T08:00:00Z',
      },
    ],
  },
  {
    id: 'c-010',
    name: 'Clara Fontaine',
    handle: '@clara-fontaine',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=96&h=96&fit=crop&crop=face',
    headline: 'CMO @ Pennylane · B2B content that converts · I study how the best SaaS brands build category authority in crowded markets',
    niche: 'B2B SaaS',
    location: 'Paris, France',
    followers: 52600,
    fitScore: 87,
    basePriceEur: 2200,
    avgImpressions: 84000,
    ctrPercent: 2.6,
    engagementRate: 3.9,
    audienceB2BPercent: 74,
    avgLeadsPerPost: 26,
    verified: false,
    responseTimeHours: 14,
    tags: ['B2B Marketing', 'Content Strategy', 'Category Creation', 'Brand', 'SaaS CMO'],
    samplePosts: [
      {
        text: 'Gong didn\'t invent revenue intelligence. They invented the category. Here\'s the 5-step playbook they used to own a space that didn\'t exist — and how any B2B CMO can replicate it.',
        likes: 3245,
        impressions: 98000,
        comments: 221,
        reposts: 534,
        postedAt: '2024-11-11T10:00:00Z',
      },
      {
        text: 'We spent €0 on paid acquisition last quarter. Our pipeline is up 34%. Here\'s how we rebuilt our content engine to generate qualified demos — not blog traffic.',
        likes: 2876,
        impressions: 87000,
        comments: 198,
        reposts: 467,
        postedAt: '2024-11-01T09:00:00Z',
      },
    ],
  },
  {
    id: 'c-011',
    name: 'Tobias Krüger',
    handle: '@tobias-krueger',
    avatarUrl: 'https://images.unsplash.com/photo-1463453091185-61582044d556?w=96&h=96&fit=crop&crop=face',
    headline: 'Partner @ EQT Ventures · 12 exits · I write about B2B SaaS unit economics, venture fundamentals & what founders get wrong about scaling',
    niche: 'B2B SaaS',
    location: 'Stockholm, Sweden',
    followers: 121400,
    fitScore: 95,
    basePriceEur: 4800,
    avgImpressions: 219000,
    ctrPercent: 3.0,
    engagementRate: 4.6,
    audienceB2BPercent: 77,
    avgLeadsPerPost: 58,
    verified: true,
    responseTimeHours: 48,
    tags: ['Venture Capital', 'SaaS Unit Economics', 'CAC Payback', 'NRR', 'Series A Scaling'],
    samplePosts: [
      {
        text: 'I\'ve reviewed 3,400 B2B SaaS decks. The companies that raise Series A in 2025 will have one thing in common: NRR above 110%. Here\'s why NRR has replaced ARR growth as the primary signal — and how to improve it fast.',
        likes: 8234,
        impressions: 267000,
        comments: 698,
        reposts: 2134,
        postedAt: '2024-11-21T08:00:00Z',
      },
      {
        text: 'CAC payback period is the metric separating fundable from unfundable B2B SaaS in 2025. Under 12 months: fundable. Over 18 months: fix before raising. Here\'s the exact model we use at EQT Ventures.',
        likes: 6543,
        impressions: 198000,
        comments: 512,
        reposts: 1654,
        postedAt: '2024-11-14T09:00:00Z',
      },
    ],
  },
  {
    id: 'c-012',
    name: 'Nadia Al-Rashid',
    handle: '@nadia-alrashid',
    avatarUrl: 'https://images.unsplash.com/photo-1479936343636-73cdc5aae0c3?w=96&h=96&fit=crop&crop=face',
    headline: 'VP Sales @ Pleo · Building the next generation of B2B sales teams in MENA & Europe · Female founders in fintech advocate',
    niche: 'GTM & Sales',
    location: 'Dubai, UAE',
    followers: 67900,
    fitScore: 86,
    basePriceEur: 2600,
    avgImpressions: 107000,
    ctrPercent: 2.6,
    engagementRate: 4.0,
    audienceB2BPercent: 79,
    avgLeadsPerPost: 33,
    verified: true,
    responseTimeHours: 16,
    tags: ['Sales Leadership', 'MENA Market', 'B2B Sales', 'Women in Tech', 'Revenue Teams'],
    samplePosts: [
      {
        text: 'The MENA B2B market is 5 years behind Silicon Valley\'s SaaS adoption curve. Which means it\'s exactly where Europe was in 2018. Here\'s why smart founders are planting flags there right now.',
        likes: 3567,
        impressions: 118000,
        comments: 234,
        reposts: 678,
        postedAt: '2024-11-18T09:00:00Z',
      },
      {
        text: 'We hired 6 women into senior sales roles this year. Our win rate went up 22%. This is not a coincidence. Here\'s the data on gender diversity in B2B sales and what it means for your hiring strategy.',
        likes: 5123,
        impressions: 163000,
        comments: 489,
        reposts: 1342,
        postedAt: '2024-11-08T10:00:00Z',
      },
    ],
  },
];

// ─── 2 Pre-Seeded Active Campaigns ──────────────────────────────────────────

export const MOCK_CAMPAIGNS: Campaign[] = [
  {
    id: 'camp-001',
    title: 'Q4 Pipeline Acceleration — DACH Enterprise',
    goal: 'Lead Generation',
    budgetEur: 24000,
    status: 'Active',
    startDate: '2024-11-01',
    endDate: '2024-12-15',
    brief:
      'We\'re targeting VP/C-Suite decision-makers at DACH-based B2B companies with 200–2000 employees. Goal is to drive demo requests for our revenue intelligence platform through authentic LinkedIn content from trusted voices in the ecosystem.',
    targetAudience: 'VP Sales, CROs, and Revenue Leaders at DACH B2B companies, 200–2000 employees',
    selectedCreators: ['c-001', 'c-003', 'c-007', 'c-011'],
    allocations: [
      {
        creatorId: 'c-001',
        allocatedBudgetEur: 7200,
        postsPlanned: 2,
        postsDelivered: 2,
        impressionsDelivered: 298000,
        clicksDelivered: 8344,
        leadsAttributed: 73,
        status: 'Approved',
      },
      {
        creatorId: 'c-003',
        allocatedBudgetEur: 5600,
        postsPlanned: 2,
        postsDelivered: 2,
        impressionsDelivered: 201000,
        clicksDelivered: 6231,
        leadsAttributed: 58,
        status: 'Approved',
      },
      {
        creatorId: 'c-007',
        allocatedBudgetEur: 4800,
        postsPlanned: 2,
        postsDelivered: 1,
        impressionsDelivered: 91000,
        clicksDelivered: 2457,
        leadsAttributed: 21,
        status: 'In Progress',
      },
      {
        creatorId: 'c-011',
        allocatedBudgetEur: 6400,
        postsPlanned: 2,
        postsDelivered: 2,
        impressionsDelivered: 441000,
        clicksDelivered: 13230,
        leadsAttributed: 112,
        status: 'Approved',
      },
    ],
    totalSpend: 19200,
    totalImpressions: 1031000,
    totalClicks: 30262,
    totalLeads: 264,
    cplEur: 72.7,
    cpmEur: 18.6,
    roas: 6.8,
  },
  {
    id: 'camp-002',
    title: 'AI Platform Launch — DevTools & Engineering Leaders',
    goal: 'Product Launch',
    budgetEur: 38000,
    status: 'Active',
    startDate: '2024-11-10',
    endDate: '2025-01-10',
    brief:
      'Launching our AI code review and security scanning platform to engineering leaders at Series B+ tech companies. We need authentic voices in the AI/ML and DevRel space who can explain technical value propositions without sounding like ads.',
    targetAudience: 'CTOs, VPs Engineering, Lead Engineers at Series B+ tech companies globally',
    selectedCreators: ['c-002', 'c-006', 'c-009'],
    allocations: [
      {
        creatorId: 'c-002',
        allocatedBudgetEur: 12300,
        postsPlanned: 3,
        postsDelivered: 2,
        impressionsDelivered: 412000,
        clicksDelivered: 14008,
        leadsAttributed: 94,
        status: 'In Progress',
      },
      {
        creatorId: 'c-006',
        allocatedBudgetEur: 15600,
        postsPlanned: 3,
        postsDelivered: 3,
        impressionsDelivered: 803000,
        clicksDelivered: 30514,
        leadsAttributed: 187,
        status: 'Approved',
      },
      {
        creatorId: 'c-009',
        allocatedBudgetEur: 10200,
        postsPlanned: 3,
        postsDelivered: 1,
        impressionsDelivered: 149000,
        clicksDelivered: 4768,
        leadsAttributed: 38,
        status: 'Brief Sent',
      },
    ],
    totalSpend: 28200,
    totalImpressions: 1364000,
    totalClicks: 49290,
    totalLeads: 319,
    cplEur: 88.4,
    cpmEur: 20.7,
    roas: 9.2,
  },
];

// ─── Helper utilities ─────────────────────────────────────────────────────────

export function getCreatorById(id: string): Creator | undefined {
  return MOCK_CREATORS.find((c) => c.id === id);
}

export function getCampaignCreators(campaign: Campaign): Creator[] {
  return campaign.selectedCreators
    .map((id) => getCreatorById(id))
    .filter((c): c is Creator => c !== undefined);
}

export function formatEur(amount: number): string {
  return new Intl.NumberFormat('de-DE', { style: 'currency', currency: 'EUR', maximumFractionDigits: 0 }).format(amount);
}

export function formatNumber(n: number): string {
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(1)}M`;
  if (n >= 1_000) return `${(n / 1_000).toFixed(1)}K`;
  return n.toString();
}

export function getNicheClass(niche: string): string {
  const map: Record<string, string> = {
    'B2B SaaS': 'badge-b2b',
    'DevRel & AI': 'badge-devrel',
    'Fintech': 'badge-fintech',
    'GTM & Sales': 'badge-gtm',
  };
  return map[niche] ?? 'badge-b2b';
}

export function getFitScoreColor(score: number): string {
  if (score >= 90) return '#10b981'; // emerald
  if (score >= 75) return '#3b82f6'; // blue
  if (score >= 60) return '#f59e0b'; // amber
  return '#f43f5e'; // rose
}
