import type { Metadata } from 'next';
import { Inter, Plus_Jakarta_Sans } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/layout/Navbar';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});

const plusJakarta = Plus_Jakarta_Sans({
  subsets: ['latin'],
  variable: '--font-plus-jakarta',
});

export const metadata: Metadata = {
  title: 'Naano: B2B LinkedIn Creator Marketplace',
  description:
    'Find the creators your buyers already trust, launch campaigns in days, and track the clicks, leads and pipeline generated by every post.',
  icons: {
    icon: '/favicon.ico',
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${inter.variable} ${plusJakarta.variable} scroll-smooth`}>
      <body className="min-h-screen text-[#090d16] font-sans antialiased selection:bg-blue-600 selection:text-white">
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}
